package lab.pvp.persistence;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import lab.pvp.model.Hero;

/** JDBC stays in the DAO; callers never need to start a database service. */
public final class H2GameDao implements GameDao {
    private final Connection connection;
    private final Gson gson = new Gson();

    public H2GameDao(Path databaseFile) {
        try {
            Path path = databaseFile.toAbsolutePath().normalize();
            Files.createDirectories(path.getParent());
            connection = DriverManager.getConnection("jdbc:h2:file:" + path.toString().replace('\\', '/') + ";DB_CLOSE_ON_EXIT=FALSE", "sa", "");
            try (Statement s = connection.createStatement()) {
                s.executeUpdate("CREATE TABLE IF NOT EXISTS decks (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(120) NOT NULL, hero VARCHAR(20) NOT NULL, cards CLOB NOT NULL, UNIQUE(name, hero))");
                s.executeUpdate("CREATE TABLE IF NOT EXISTS matches (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, played_at VARCHAR(64) NOT NULL, player1 VARCHAR(20) NOT NULL, player2 VARCHAR(20) NOT NULL, winner INT NOT NULL, turns INT NOT NULL, battle_log CLOB)");
                s.executeUpdate("CREATE TABLE IF NOT EXISTS profiles (name VARCHAR(120) PRIMARY KEY, preferred_hero VARCHAR(20) NOT NULL)");
            }
        } catch (Exception e) { throw failure("Cannot open game database", e); }
    }

    @Override public synchronized SavedDeck saveDeck(String name, Hero hero, List<String> cards) {
        try (PreparedStatement s = connection.prepareStatement("MERGE INTO decks(name,hero,cards) KEY(name,hero) VALUES(?,?,?)")) {
            s.setString(1, name); s.setString(2, hero.name()); s.setString(3, gson.toJson(cards)); s.executeUpdate();
            return decks(hero).stream().filter(d -> d.name().equals(name)).findFirst().orElseThrow();
        } catch (SQLException e) { throw failure("Could not save deck", e); }
    }

    @Override public synchronized List<SavedDeck> decks(Hero hero) {
        List<SavedDeck> result = new ArrayList<>();
        try (PreparedStatement s = connection.prepareStatement("SELECT id,name,hero,cards FROM decks WHERE hero=? ORDER BY id DESC")) {
            s.setString(1, hero.name());
            try (ResultSet r = s.executeQuery()) {
                while (r.next()) result.add(new SavedDeck(r.getLong(1), r.getString(2), Hero.valueOf(r.getString(3)), gson.fromJson(r.getString(4), new TypeToken<List<String>>() {}.getType())));
            }
            return List.copyOf(result);
        } catch (SQLException e) { throw failure("Could not load decks", e); }
    }

    @Override public synchronized void saveMatch(MatchRecord match, String log) {
        try (PreparedStatement s = connection.prepareStatement("INSERT INTO matches(played_at,player1,player2,winner,turns,battle_log) VALUES(?,?,?,?,?,?)")) {
            s.setString(1, match.playedAt()); s.setString(2, match.player1().name()); s.setString(3, match.player2().name());
            s.setInt(4, match.winner()); s.setInt(5, match.turns()); s.setString(6, log); s.executeUpdate();
        } catch (SQLException e) { throw failure("Could not save match", e); }
    }

    @Override public synchronized List<MatchRecord> history() {
        List<MatchRecord> result = new ArrayList<>();
        try (Statement s = connection.createStatement(); ResultSet r = s.executeQuery("SELECT id,played_at,player1,player2,winner,turns FROM matches ORDER BY id DESC LIMIT 100")) {
            while (r.next()) result.add(new MatchRecord(r.getLong(1), r.getString(2), Hero.valueOf(r.getString(3)), Hero.valueOf(r.getString(4)), r.getInt(5), r.getInt(6)));
            return List.copyOf(result);
        } catch (SQLException e) { throw failure("Could not read history", e); }
    }

    @Override public synchronized void saveProfile(String name, Hero hero) {
        try (PreparedStatement s = connection.prepareStatement("MERGE INTO profiles(name,preferred_hero) KEY(name) VALUES(?,?)")) {
            s.setString(1, name); s.setString(2, hero.name()); s.executeUpdate();
        } catch (SQLException e) { throw failure("Could not save profile", e); }
    }

    @Override public synchronized List<String> profiles() {
        List<String> result = new ArrayList<>();
        try (Statement s = connection.createStatement(); ResultSet r = s.executeQuery("SELECT name FROM profiles ORDER BY name")) {
            while (r.next()) result.add(r.getString(1));
            return List.copyOf(result);
        } catch (SQLException e) { throw failure("Could not read profiles", e); }
    }

    @Override public synchronized void close() {
        try { connection.close(); } catch (SQLException e) { throw failure("Could not close database", e); }
    }

    private static IllegalStateException failure(String message, Exception cause) {
        return new IllegalStateException(message + ": " + cause.getMessage(), cause);
    }
}
